articles/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from .api import  ArticleApi,ArticleCreateApi,ArticleUpdateApi,ArticleDeleteApi

app_name = "article"

urlpatterns = [
    path('', views.index, name = "index"),
    path('dashboard/', views.dashboard, name = "dashboard"),

    path('list/', views.listCar, name = "listCar"),
    path('car/<int:id>',views.detail,name = "detail"),
    path('create/', views.createCar, name = "createCar"),
    path('update/<int:id>',views.updateCar,name = "update"),
    path('delete/<int:id>',views.deleteCar,name = "delete"),
    
    path('contact/', views.contact, name = "contact"),
    path('contact/<int:id>', views.updateContact, name = "updateContact"),

    # API
    path('api/',ArticleApi.as_view()),
    path('api/create',ArticleCreateApi.as_view()),
    path('api/<int:pk>',ArticleUpdateApi.as_view()),
    path('api/<int:pk>/delete',ArticleDeleteApi.as_view()),


    
]
urlpatterns = format_suffix_patterns(urlpatterns)

base/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("articles.urls")),
    path('user/', include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/cartable.html
{% if articles %}

<div id="carListA" class="row" data-count="{{carCount}}">

    {% for article in articles %}
    <div class="col-md-6 col-lg-4 mt-2" >
        <div class="CarPic">
            <div><p>{{article.price}} TL</p></div>
            {% if article.pic %}
            <img src="{{article.pic.url}}" class="img-thumbnail" alt="">
            {% else %}
            <img src="../static/img/favicon.jpg" class="img-thumbnail" alt="">

            {% endif %}
            
        </div>
        <div class="spesific">
            <h5> <a href="{% url 'article:detail' article.id %}">{{article.make}} - {{article.model}}</a></h5>

            <ul>
                <li><span>{{article.year}}</span></li>
                <li><span>{{article.transmission}}</span></li>
                <li><span>{{article.fuelType}}</span></li>
            </ul>
            <br>
            <hr>
            <table class="table table-dark">
                <tbody>
                    <tr>
                        <td>Kilometre</td>
                        <td>{{article.km}}</td>
                    </tr>
                    <tr>
                        <td>Motor</td>
                        <td>{{article.engine}}</td>
                    </tr>
                    <tr>
                        <td>Paket</td>
                        <td>{{article.variant}}</td>
                    </tr>
                    <tr>
                        <td>Eklenme Tarihi</td>
                        <td>{{article.date |date:"Y-m-d"}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
    

templates/includes/dashtable.html
{% if articles %}

<table  class="table table-dark">
    <thead >
        <tr>
            <td>Id</td>
            <td>Marka</td>
            <td>Model</td>
            <td>Satış</td>
            <td>Güncelle</td>
            <td>Sil</td>
        </tr>
    </thead>
    <tbody>
        
        
        {% for article in articles %}
        <tr>
            <td><a href="{% url 'article:detail' article.id %}">{{article.id}}</a></td>
            <td>{{article.make}}</td>
            <td>{{article.model}}</td>
            {% if article.isSold == False %}
            <td class="status">Listelenmiş</td>
            {% else %}
            <td><button class="btn btn-danger" >Satılmış</button></td>
            {% endif %}
            <td><a href="{% url 'article:update' article.id %}" class="btn btn-danger" type="button">Güncelle</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger" type="button">Sil</a></td>
        </tr>
            
        {% endfor %}
            
            
    </tbody>
</table>

{% else %}

<button class="btn btn-info" type="button">Eklenmiş Kaydınız Bulunamadı</button>
    
{% endif %}
    

<script>
/*    $( ".status" ).mouseover(function() {
        $(this).text( "Satıldı" );
    });
    $( ".status" ).mouseout(function() {
        $(this).text( "Listelenmiş" );
    });
  */  
</script>

templates/includes/navbar.html
<nav>
    <a href="{% url 'article:index' %}"><span>Golden</span>Cars</a>
    <ul>
        <li><a href="{% url 'article:contact' %}">İletişim</a></li>
        <li><a href="{% url 'article:listCar' %}">Satıştaki Araçlar</a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'article:dashboard' %}">Dashboard</a></li>
        {% endif %}
    </ul>
</nav>

templates/includes/navbarold.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'article:index' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:carlist' %}">Liste <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          {% if request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'article:dashboard' %}">Dashboard</a>
          {% endif %}
            
        </li>
      </ul>
    </div>
    </div>
  </nav>

<style>
  nav{
    
  }
</style>