base/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("articles.urls")),
    path('user/', include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

FuelTypes = {
    ("Benzin","Benzin"),
    ("Benzin Lpg","Benzin Lpg"),
    ("Dizel","Dizel"),
    ("Elektrik","Elektrik"),
    ("Hybrid","Hybrid"),
}
BodyTypes = {
    ("Sedan","Sedan"),
    ("Suv","Suv"),
    ("Hathcback","Hathcback"),
    ("Crossover","CrossOver"),
    ("Diğer","Diğer"),
}
Transmission = {
    ("Otomatik","Otomatik"),
    ("Yarı Otomatik","Yarı Otomatik"),
    ("Manuel","Manuel"),
    
}


class Article(models.Model):

    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Ekleyen")
    pic = models.FileField(blank=True,null=True,verbose_name="Fotoğraf")
    year = models.PositiveIntegerField(default=2020,validators=[MaxValueValidator(2021),
            MinValueValidator(1980)],verbose_name="Yıl")
    km = models.PositiveIntegerField(verbose_name="Km")
    price = models.PositiveIntegerField(verbose_name="Fiyat")
    make = models.CharField(max_length = 20,verbose_name="Marka")
    model = models.CharField(max_length = 20,verbose_name="Model")
    transmission = models.TextField(choices=Transmission,verbose_name="Vites")
    fuelType = models.TextField(choices=FuelTypes,verbose_name="Yakıt")
    bodyType = models.TextField(choices=BodyTypes,verbose_name="Kasa")
    engine = models.CharField(blank=True,null=True,max_length = 20,verbose_name="Motor")
    variant = models.CharField(blank=True,null=True,max_length = 20,verbose_name="Paket")
    content = RichTextField(blank=True,null=True,verbose_name="Detay")
    isSold = models.BooleanField(default=False,verbose_name="Durum")
    highlighted = models.BooleanField(default=False,verbose_name="Öne Çıkar")
    date = models.DateTimeField(auto_now_add=True,verbose_name="Tarih")

    def __str__(self):
        return self.make
    class Meta:
        ordering = ['-date']

ReplyOption = {
    ("Mail","Mail"),
    ("Telefon","Telefon")
} 
      
    
class Message (models.Model):

    nameSurname = models.CharField(max_length=25, verbose_name="Ad Soyad")
    replyOption = models.TextField(default="Mail",choices=ReplyOption,blank=True,null=True,verbose_name="Nasıl dönüş yapalım")
    phone = models.CharField(max_length=11,blank=True,null=True,verbose_name="Telefon")
    mail = models.CharField(max_length=30,blank=True,null=True,verbose_name="Mail")
    subject= models.TextField(blank=False,null=False,max_length=20,verbose_name="Konu")
    notes = RichTextField(blank=True,null=True,verbose_name="Notlar")
    isDone = models.BooleanField(default=False,verbose_name="Dönüş Yapıldı")
    date = models.DateTimeField(auto_now_add=True,verbose_name="Tarih")

    def __str__(self):
        return self.nameSurname
    class Meta:
        ordering = ['-date']


    



    




    

templates/contact/contact.html
{% extends 'layout.html' %}


{% block body %}
{% load static %}
{% load crispy_forms_tags %}
<form method="post" style="padding:0px 10%;" class="mt-3" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-lg-4">
            {{form.media}}
            {{form|crispy}}
            <button type = "submit" class="btn btn-primary">Gönder</button>
        </div>
        <div id="ContactImg" class="col-lg-8 ">
            <img style="width: 100%;" src="{% static 'img/Contact.jpg' %}" alt="">
        </div>
    </div>
    
    
</form>

<script>
    $(document).ready(function(){
        $('#div_id_phone').hide()
    })
    $('#id_replyOption').change(function(){
        if ($(this).val() == "Telefon"){
            $('#div_id_mail').hide()
            $('#div_id_phone').show()
        }
        else{
            $('#div_id_phone').hide()
            $('#div_id_mail').show()

        }
    })
</script>
<style>
    label{
        color:#1773cf;
        font-weight: bold;
    }
    @media only screen and (max-width: 991px) {
        #ContactImg{
            display: none;
        }
        button {
            margin-bottom: 40px;
        }
  }
</style>
    
{% endblock body %}
    

templates/contact/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Ticket Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Ticket Güncelle</button>
        </form>
    </div>
  </div>


{% endblock body %}