articles/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from .api import  ArticleApi,ArticleCreateApi,ArticleUpdateApi,ArticleDeleteApi

app_name = "article"

urlpatterns = [
    path('', views.index, name = "index"),
    path('dashboard/', views.dashboard, name = "dashboard"),

    path('list/', views.listCar, name = "listCar"),
    path('car/<int:id>',views.detail,name = "detail"),
    path('create/', views.createCar, name = "createCar"),
    path('update/<int:id>',views.updateCar,name = "update"),
    path('delete/<int:id>',views.deleteCar,name = "delete"),
    
    path('contact/', views.contact, name = "contact"),
    path('contact/<int:id>', views.updateContact, name = "updateContact"),

    # API
    path('api/',ArticleApi.as_view()),
    path('api/create',ArticleCreateApi.as_view()),
    path('api/<int:pk>',ArticleUpdateApi.as_view()),
    path('api/<int:pk>/delete',ArticleDeleteApi.as_view()),


    
]
urlpatterns = format_suffix_patterns(urlpatterns)

base/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("articles.urls")),
    path('user/', include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard.html
{% extends 'layout.html' %}


{% block body %}
{% load static %}

<div id="DashMain" >
    <div class="row">
        <div class="col-md-8">
            <div class="Fp">
                <div class="row">
                    
                    {% if replies %}
                    {% for reply in replies %}
                    <div class="col-md-2">
                        
                        {% if reply.isDone == False %}
                        <div class="Contact" style="border: solid 2px #1479FF;">
                            <div class="row">
                                <img src="{% static 'img/Contact.svg' %}" height="30px" alt="">
                            </div>
                            <div class="row">
                                <p class="ShowSubject" data-message="{{reply.subject}}">{{reply.nameSurname}}</p>
                                
                            </div>
                            <div class="row">
                                {% if reply.phone %}
                                <span href="">Telefon </span>
                                {% else %}
                                <span href="">Mail </span>
                                {% endif %}
                            </div>
                            <div class="row">
                                <a href="{% url 'article:updateContact' reply.id %}">Detay</a>
                            </div>
                        </div>
                        
                        {% else %}
                        <div class="Contact" style="border: solid 2px #1479FF;">
                            <div class="row">
                                <img src="{% static 'img/Contact.svg' %}" height="30px" alt="">
                            </div>
                            <div class="row">
                                <p class="ShowSubject" data-message="{{reply.subject}}">{{reply.nameSurname}}</p>
                            </div>
                            <div class="row">
                                {% if reply.phone %}
                                <span href="">Telefon </span>
                                {% else %}
                                <span href="">Mail </span>
                                {% endif %}
                            </div>
                            <div class="row">
                                <a href="{% url 'article:updateContact' reply.id %}">Detay</a>
                            </div>
                        </div>

                        {% endif %}
                            
                        
                    </div>



                    {% endfor %}
                    <script>
                        $('.ShowSubject').click(function(){
                            var data = $(this).attr("data-message")
                            alert(data)
                        })
                    </script>
                    {% else %}
                    <p style="width: 100%;text-align: center;padding-top: 30px;font-weight: bold;">Yeni Mesaj Yok</p>
                    {% endif %}
                        
                    
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="Fp" >
                <a href="{% url 'article:createCar' %}" class="btn btn-primary my-1">Mesajlar</a>
                <a href="{% url 'article:createCar' %}" class="btn btn-dark my-1">Araç Ekle</a>
                <a href="{% url 'article:createCar' %}" class="btn btn-dark my-1">Araçlar</a>
                <a href="{% url 'article:createCar' %}" class="btn btn-dark my-1">Satılan Araçlar</a>
            </div>
        </div>
        
       
    </div>
    {% include 'includes/dashtable.html' %}
</div>


{% endblock body %}

templates/dashboardold.html
{% extends 'layout.html' %}


{% block body %}

<div id="DashMain">
    
    <div class="row">

        {% if user.is_superuser %}

        <div class="col-lg-8">
            <p>Hoşgeldiniz: {{request.user}}</p>
            <a href="{% url 'article:createCar' %}" class="btn btn-danger my-2">Yeni Ekle</a>
            {% include 'includes/dashtable.html' %}
        </div>
        <div class="col-lg-4">
            <p>En son mesajlar</p>
            <table class="table table-dark">
                <thead>
                    <tr>
                        <td>İsim</td>
                        <td>Detay</td>
                        <td>Tarih</td>
                    </tr>
                </thead>
                <tbody>

                    {% for message in replies %}
                    {% if message.isDone == False %}
                    <tr class="table-danger">
                        <td><a class="ma" data-message="{{message.subject}}">{{message.nameSurname}}</a></td>
                        <td><a href="{% url 'article:updateContact' message.id %}">Git</a></td>
                        <td>{{message.date |date:"Y-m-d"}}</td>
                    </tr>
                    {% else %}
                    <tr class="table-success">
                        <td><a class="ma" data-message="{{message.subject}}">{{message.nameSurname}}</a></td>
                        <td><a href="{% url 'article:updateContact' message.id %}">Git</a></td>
                        <td>{{message.date |date:"Y-m-d"}}</td>

                    </tr>
                    {% endif %}

                    {% endfor %}

                    <script>
                        $('.ma').click(function () {
                            var data = $(this).attr("data-message")
                            alert(data)
                        })
                    </script>
                </tbody>
            </table>
        </div>
        {% else %}
        <p>Hoşgeldiniz: {{request.user}}</p>
            <a href="{% url 'article:createCar' %}" class="btn btn-danger my-2">Yeni Ekle</a>
        {% include 'includes/dashtable.html' %}

        {% endif %}

    </div>

</div>


{% endblock body %}

templates/index.html
{% extends 'layout.html' %}


{% block body %}

<div id="Landing"  >
    <div class="col-md-4 ">
        <h4>Her araba özeldir,<br>
            sizin tercihiniz <br> nasıl ? </h4>
    </div>
    <div class="col-md-8 col-lg-8" >
        <a href="{% url 'article:listCar' %}" id="quickfind" type ="submit"> Aramaya başla </a>
    </div>
    
</div>
    
{% endblock body %}
    

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <title>Goldens: Hızlı tutkulu hatasız</title>
</head>

<body>

    {% include 'includes/navbar.html' %}

    {% if messages %}
    <div class="container mt-2"></div>

    {% for message in messages %}
    {% if message.tags == "info" %}
    <div class="alert alert-danger">{{ message }}</div>
    {% else %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

    {% endif %}


    {% endfor %}
    </div>
    {% endif %}


    <div>
        {% block body %}
        {% endblock body %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
</body>

</html>